project:
  type: website
  output-dir: docs

website:
  title: "Research Lab of Shen Cheng, Ph.D."
  navbar:
    background: "#7A0019"
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - teaching.qmd
      - blogs.qmd

format:
  html:
    theme: yeti
    mainfont: arial
    monofont: courier new
    css: styles.css
    toc: true



