project:
  type: website
  output-dir: docs

website:
  title: "Cheng Lab"
  navbar:
    background: "#7A0019"
    left:
      - href: index.qmd
        text: Home
      - blogs.qmd

format:
  html:
    theme: yeti
    mainfont: arial
    monofont: courier new
    css: styles.css
    toc: true



