---
title: "Teaching"
toc: false
---

## ECP8506 Clinical Trial Simulations 

**Course Overview**

Precision medicine is an emerging field aiming to customize the patients’ treatment plans according to individual characteristics. Recently, the rapid growth of the discipline of quantitative pharmacology (i.e., pharmacometrics) facilitates the realization of precision medicine. Diving into the concepts of pharmacometric simulations, this course explores how model-based strategies can drive quantitative decision-making in either clinical drug research or personalized therapeutics. 

<!-- Students will gain familiarity with contemporary pharmacometric tools, including various software suites and computational platforms. Throughout the course, participants will be asked to attend lecture series, perform hands-on simulation exercises based on hypothetical clinical scenarios, participate in small group discussions, and learn real-world case studies of model-informed drug development (MIDD) and model-informed precision dosing (MIPD). -->

**Materials**

-   [2024 Fall](https://github.com/UMN-ECP-PMX/ecp8506)


## Pharmacometrics Coffee Break

**Overview**

An informal pharmacometric discussion group involving a diverse group of moderators, presenters and audience.If you are interested in participating, please contact Shen Cheng (<cheng423@umn.edu>). 

**Topic list**

::: {.callout-note collapse="true"}
## 2025

| Date       | Topic            | Moderator |
| --------   | -------          | -------   |
| 03/14/2025 | Topic discussion | Shen      |
| 03/28/2025 | PK               | xxx       |
| 04/11/2025 | PD               | yyy       |
:::

::: {.callout-note collapse="true"}
## 2026

<!-- This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default. -->
:::
